package com.squareup.leakcanary;
//Copyright 2015 The Chromium Authors. All rights reserved.
//Use of this source code is governed by a BSD-style license that can be
//found in the LICENSE file.
//Normally generated by Gradle.
public class LeakcanaryBuildConfig {
	 public static final String LIBRARY_VERSION = "1.5";
	 public static final String GIT_SHA = "unknown"; // Unlikely to be kept up-to-date, so don't try.
}